# Generated by Django 3.2.9 on 2021-12-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreoperation', models.CharField(max_length=200, null=True, verbose_name='titre operation')),
                ('entreprise', models.CharField(max_length=200, null=True, verbose_name='entreprise')),
                ('annee_de_livraison', models.CharField(max_length=200, null=True, verbose_name='annee de livraison')),
                ('ville', models.CharField(max_length=200, null=True, verbose_name='ville')),
                ('mandataire', models.CharField(max_length=200, null=True, verbose_name='mandaaire')),
                ('ppi', models.CharField(max_length=200, null=True, verbose_name='ppi')),
                ('lycee', models.CharField(max_length=200, null=True, verbose_name='lyce')),
                ('notification_du_marche', models.CharField(max_length=200, null=True, verbose_name='notification du marche')),
                ('codeuai', models.CharField(max_length=200, null=True, verbose_name='codeuai')),
                ('longitude', models.FloatField(null=True, verbose_name='longitude')),
                ('etat_d_avancement', models.CharField(max_length=200, null=True, verbose_name='etat_d_avancement')),
                ('montant_des_ap_votes_en_meu', models.FloatField(null=True, verbose_name='montant des ap votes en meu')),
                ('cao_attribution', models.CharField(max_length=200, null=True, verbose_name='cao_attribution')),
                ('latitude', models.FloatField(null=True, verbose_name='latitude')),
                ('maitrise_d_oeuvre', models.CharField(max_length=200, null=True, verbose_name='maitrise_d_oeuvre')),
                ('mode_de_devolution', models.CharField(max_length=200, null=True, verbose_name='mode_de_devolution')),
                ('annee_d_individualisation', models.CharField(max_length=200, null=True, verbose_name='annee_d_individualisation')),
                ('enveloppe_prev_en_meu', models.FloatField(null=True, verbose_name='enveloppe prev en meu')),
                ('nombre_de_lots', models.IntegerField(null=True, verbose_name='nombre_de_lots')),
            ],
        ),
    ]
